apiVersion: v1
kind: Service
metadata:
  namespace: blog
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
