apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: blog
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: martinheinz/blog_frontend:latest
        name: frontend
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
